# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  build:
     # if: github.event.review.state == 'approved'
     runs-on: [self-hosted]
     
     steps:
       # Runs a single command using the runners shell
       - name: Checkout Sources
         uses: actions/checkout@v3
