# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    types: [labeled, ready_for_review]
  pull_request_review:
    types: [edited, dismissed, submitted]
  workflow_dispatch:

jobs:
  build:
     # if: github.event.review.state == 'approved'
     runs-on: [self-hosted]
     
     steps:
        # Check number of reviews
       - id: 'reviews'
         uses: jrylan/github-action-reviews-counter@v1.0.0

       # Checkout
       - name: Checkout Sources
         uses: actions/checkout@v3
         
       - name: Setup Node
         uses: actions/setup-node@v1
         with:
            version: 12
        
       - name: Install Octokit
         run: npm install @octokit/action
       
       - name: Run Fastlane Autotest
         run: fastlane autotest
