# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  build:
     # if: github.event.review.state == 'approved'
     runs-on: [self-hosted]
     
     steps:
       # Checkout
       - name: Checkout Sources
         uses: actions/checkout@v3
         
       - name: Setup Node
         uses: actions/setup-node@v1
         with:
            version: 12
        
       - name: Install Octokit
         run: npm install @octokit/action
       
       - name: Run Fastlane Autotest
         run: fastlane autotest
