# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [labeled, ready_for_review]
  pull_request_review:
    types: [edited, dismissed, submitted]

jobs:
  echo:
    if: ${{ github.event.action }} == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: echo 'Some Text'
      
  check:    
    runs-on: [self-hosted]
    outputs:
      status: ${{ steps.approved.outputs.approved == 'true' }}
    steps:
    - uses: luisrjaeger/approved-event-checker@1.0.0
      id: approved
      with:
        approvals: 2
        check_changes_requested: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}     

  build:
    runs-on: [self-hosted]
    needs: check
 
    if:  ${{ needs.check.outputs.status == 'true' }}
     
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run Fastlane Autotest
      run: fastlane autotest
