# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request:
    types: [labeled, ready_for_review]
  pull_request_review:
    types: [edited, dismissed, submitted]

jobs:
  build:
     # if: github.event.review.state == 'approved'
     runs-on: [self-hosted]
     
     steps:
        # Check number of reviews
       - id: 'reviews'
         uses: jrylan/github-action-reviews-counter@v1.0.0
         with:
          repo-token: '${{ secrets.TOKEN }}'
         
       - name: Check approvals
         if: 'steps.reviews.outputs.approved <= 1 && steps.reviews.outputs.changes_requested > 0'
         run: exit 1

       - name: Checkout
         uses: actions/checkout@v3

       - name: Run Fastlane Autotest
         run: fastlane autotest
