# This is a basic workflow to help you get started with Actions

name: CI

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:
  build:
     # if: github.event.review.state == 'approved'
     runs-on: [Github]
     
     steps:
       # Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world!
